package View.GUI;

import Controller.Controller;
import Controller.WordControl;
import Model.Word;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Nguyễn Phúc
 */
public class AddDialog extends javax.swing.JFrame {
    
    private Controller mainController;
    private WordControl Controller;
    // Icon true
    ImageIcon iconTrue = new ImageIcon("IconTrue.png");

    /**
     * Creates new form AddDialog
     */
    public AddDialog(Controller controller) {
        this.mainController = controller;
        this.Controller = controller.getWordController();
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbOK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jfWord = new javax.swing.JTextField();
        jfMeaning = new javax.swing.JTextField();
        jbCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jfPronunce = new javax.swing.JTextField();

        setTitle("Add Word");
        setResizable(false);

        jbOK.setText("OK");
        jbOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Word:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Meaning:");

        jfWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfWordActionPerformed(evt);
            }
        });

        jfMeaning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfMeaningActionPerformed(evt);
            }
        });

        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Pronunciation:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jfPronunce))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jbOK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jbCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jfMeaning, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(jfWord))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbCancel, jbOK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jfWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jfMeaning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jfPronunce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOK)
                    .addComponent(jbCancel))
                .addGap(32, 32, 32))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbCancel, jbOK});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Tạo sự kiện cho jbOK
     *
     * @param evt Sự kiện
     */
    private void jbOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOKActionPerformed
        if (jfWord.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập từ cần thêm.", "Error", JOptionPane.ERROR_MESSAGE);
            jfWord.requestFocus();
            return;
        }
        if (jfMeaning.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Chưa nhập nghĩa từ cần thêm.", "Error", JOptionPane.ERROR_MESSAGE);
            jfMeaning.requestFocus();
            return;
        }
        String Name = jfWord.getText();
        String Meaning = jfMeaning.getText();
        String Pronunce = jfPronunce.getText();
        
        this.setVisible(false);
        jfWord.setText("");
        jfWord.requestFocus();
        jfMeaning.setText("");
        if (this.Controller.addNewWord(new Word(Name, Meaning, Pronunce))) {
            JOptionPane.showMessageDialog(null, "Thêm từ thành công!", "Information", JOptionPane.INFORMATION_MESSAGE, iconTrue);
        } else {
            JOptionPane.showMessageDialog(null, "Từ đã tồn tại.", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        this.mainController.updateView();
    }//GEN-LAST:event_jbOKActionPerformed

    /**
     * Tạo sự kiện cho jbCancel
     *
     * @param evt Sự kiện
     */
    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        this.setVisible(false);
        jfWord.setText("");
        jfWord.requestFocus();
        jfMeaning.setText("");
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jfMeaningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfMeaningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfMeaningActionPerformed

    private void jfWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfWordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOK;
    private javax.swing.JTextField jfMeaning;
    private javax.swing.JTextField jfPronunce;
    private javax.swing.JTextField jfWord;
    // End of variables declaration//GEN-END:variables

    /**
     * Cài đặt icon
     */
    private void setIcon() {
        ImageIcon icon = new ImageIcon("src/View/TitleIcons/IconAdd.png");
        setIconImage(icon.getImage());
    }
}
