package View.GUI;

import Controller.Controller;
import Controller.WordControl;
import Model.Word;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import static java.lang.Math.random;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyễn Phúc
 */
public class LearningDialog extends javax.swing.JFrame {
    
    private Controller mainController;
    private WordControl Controller;
    
    private int NUMBER_OF_WORD_FOR_LECTURE = 10;
    private Word currentWord = null;
    private ArrayList<Word> lecture = null;
    private int currentProgress = 0;
    private final int MAX_PROGRESS = 100;
    // Biến cho phép sinh ngẫu nhiên
    Random random = new Random();

    /**
     * Creates new form LearningDialog
     */
    public LearningDialog(Controller controller) {
        this.mainController = controller;
        this.Controller = controller.getWordController();
        initComponents();
        setIcon();
        setBackground();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                setVisible(false);
                HomeScreen homeScreen = new HomeScreen(controller);
                homeScreen.setVisible(true);
            }
        });
        setupLecture();
    }
    
    private void setupLecture() {
        if(lecture == null) {
            lecture = new ArrayList<Word>();
        }
        int numOfWord = Controller.getListWord().size();
        if(numOfWord <= NUMBER_OF_WORD_FOR_LECTURE) {
            NUMBER_OF_WORD_FOR_LECTURE = numOfWord;
        }
        for(int i = 0; i < NUMBER_OF_WORD_FOR_LECTURE; ++i) {
            lecture.add(Controller.getWord(random.nextInt(numOfWord)));
        }
        currentWord = lecture.get(0);
        setNewWordToLearn(currentWord);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbStop = new javax.swing.JButton();
        jbNext = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlWord = new javax.swing.JLabel();
        jPronunce = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMeaning = new javax.swing.JTextArea();
        jWordProgress = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jProgressLearning = new javax.swing.JProgressBar();

        setTitle("Learning");
        setResizable(false);

        jbStop.setText("Stop");
        jbStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStopActionPerformed(evt);
            }
        });

        jbNext.setText("Next");
        jbNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNextActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(33, 242, 128));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlWord.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jlWord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlWord.setText("jLabel1");
        jlWord.setAlignmentX(0.5F);
        jlWord.setAutoscrolls(true);

        jPronunce.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jPronunce.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPronunce.setText("jLabel2");

        jMeaning.setEditable(false);
        jMeaning.setColumns(20);
        jMeaning.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jMeaning.setLineWrap(true);
        jMeaning.setRows(5);
        jMeaning.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jMeaning);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Word learning's progress");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPronunce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jWordProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlWord, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPronunce, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jWordProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jProgressLearning.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jbStop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbNext, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProgressLearning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbNext, jbStop});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jProgressLearning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbStop)
                    .addComponent(jbNext))
                .addGap(14, 14, 14))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbNext, jbStop});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setNewWordToLearn(Word newWord) {
        this.currentWord = newWord;
        jlWord.setText(newWord.getName());
        jMeaning.setText(newWord.getMeaning());
        jPronunce.setText(newWord.getPronunciation());
        jWordProgress.setValue(newWord.getLearnProgress() * 20);
        jProgressLearning.setValue(currentProgress);
        currentProgress += 10;
    }
    
    private boolean isCompleteLecture() {
        boolean complete = true;
        if(currentProgress <= MAX_PROGRESS) {
            complete = false;
        }
        return complete;
    }
    
    /**
     * Tạo sự kiện cho jbNext
     *
     * @param evt Sự kiện
     */
    private void jbNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNextActionPerformed
        if(!isCompleteLecture()) {
            this.currentWord = lecture.get((this.currentProgress/10) % lecture.size());
            this.currentWord.increaseProgress();
            setNewWordToLearn(this.currentWord);
        } else {
            Controller.updateWord(lecture);
            int reply = JOptionPane.showConfirmDialog(null, "Learning done\nContinue?", "Continue", JOptionPane.YES_NO_OPTION);
            if(reply == JOptionPane.YES_OPTION) {
                setupLecture();
                currentProgress = 0;
                return;
            }
            this.setVisible(false);
            HomeScreen homeScreen = new HomeScreen(mainController);
            homeScreen.setVisible(true);
        }
    }//GEN-LAST:event_jbNextActionPerformed

    /**
     * Tạo sự kiện cho jbStop
     *
     * @param evt Sự kiện
     */
    private void jbStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStopActionPerformed
        Controller.updateWord(lecture);
        this.setVisible(false);
        HomeScreen homeScreen = new HomeScreen(mainController);
        homeScreen.setVisible(true);
    }//GEN-LAST:event_jbStopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jMeaning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressLearning;
    private javax.swing.JLabel jPronunce;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar jWordProgress;
    private javax.swing.JButton jbNext;
    private javax.swing.JButton jbStop;
    private javax.swing.JLabel jlWord;
    // End of variables declaration//GEN-END:variables

    /**
     * Cài đặt Icon
     */
    private void setIcon() {
        ImageIcon icon = new ImageIcon("src/View/TitleIcons/IconLearningDialog.png");
        setIconImage(icon.getImage());
    }

    /**
     * Cài đặt background
     */
    private void setBackground() {
        getContentPane().setBackground(new Color(109, 255, 179));
    }
}
